services:
  db:
    image: postgres:15-alpine
    container_name: wallet_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: wallet_api_homolog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wallet_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: gilguerra/wallet_api:latest
    container_name: wallet_api
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123
      DB_NAME: wallet_api_homolog
      DB_DRIVER: postgresql+psycopg2
      TAXA_SAQUE_PERCENTUAL: 0.01
      TAXA_CONVERSAO_PERCENTUAL: 0.02
      TAXA_TRANSFERENCIA_PERCENTUAL: 0.01
      COINBASE_API_BASE_URL: https://api.coinbase.com/v2/prices
      SECRET_KEY: your-secret-key-here
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      PRIVATE_KEY_SIZE: 32
      PUBLIC_KEY_SIZE: 32
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - wallet_network

volumes:
  postgres_data:

networks:
  wallet_network:
    driver: bridge
